# se servirá una página elaborada con vuejs para registrar 
# la entrega del servicio de alimentación

# ---- multistage build
# https://docs.docker.com/develop/develop-images/multistage-build/

# ---------- BUILD STAGE -----------
# seleccionando una imagen que contenga node
FROM mysql:latest