name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: backend/pyproject.toml
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v03
      #- name: Checkout code
      #  uses: actions/checkout@v2
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd backend
          pip install -e .[test]
      - name: Lint
        run: bash app/scripts/lint.sh
      #- name: Test with inv
      #  run: inv cover qa # inv helps you investigate IPs/hosts and DNS records then returns the results in a copy/pasteable format.
      #- name: Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    file: ./backend/coverage.xml