name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: backend/pyproject.toml
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v03
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd backend
          pip install -e .[test]
      - name: Lint
        run: |
          cd backend
          bash scripts/lint.sh
      - name: Generate coverage report
        run: |
          cd backend
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./backend/coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./backend/coverage1.xml,./backend/coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./backend/coverage/codecov_report.txt
          verbose: true